### ISSUE TITLE
Embed Video Time activity for TinyMCE generates an error when editing text block on default dashboard in Moodle Workplace

### ISSUE THREAD

**Issue by superfoght** [bdecentgmbh/moodle-mod_videotime#89]
Note: I haven't tested this on regular Moodle LMS - only on Moodle Workplace

Steps to reproduce:
1) Make sure the Embed Video Time activity for TinyMCE plugin is installed and activated and that you use the TinyMCE plugin
2) Go to the default dashboard page editing screen - either in the system level or on a specific tenant
3) Edit the default dashboard. 
4) Add a text block and type in some content
5) When it is added, try to edit the block
6) The error: Context does not belong to any course occur. 
If you turn on debugging you get this error:

Error code: codingerror
* line 977 of /lib/classes/context.php: coding_exception thrown
* line 152 of /lib/classes/context/block.php: call to core\context->get_course_context()
* line 56 of /lib/editor/tiny/plugins/videotime/classes/plugininfo.php: call to core\context\block->get_course_context()
* line 64 of /lib/editor/tiny/classes/manager.php: call to tiny_videotime\plugininfo::is_enabled()
* line 199 of /lib/editor/tiny/classes/editor.php: call to editor_tiny\manager->get_plugin_configuration()
* line 433 of /lib/form/editor.php: call to editor_tiny\editor->use_editor()
* line 192 of /lib/pear/HTML/QuickForm/Renderer/Tableless.php: call to MoodleQuickForm_editor->toHtml()
* line 3502 of /lib/formslib.php: call to HTML_QuickForm_Renderer_Tableless->renderElement()
* line 432 of /lib/pear/HTML/QuickForm/element.php: call to MoodleQuickForm_Renderer->renderElement()
* line 1644 of /lib/pear/HTML/QuickForm.php: call to HTML_QuickForm_element->accept()
* line 2130 of /lib/formslib.php: call to HTML_QuickForm->accept()
* line 1687 of /lib/pear/HTML/QuickForm.php: call to MoodleQuickForm->accept()
* line 445 of /lib/pear/HTML/Common.php: call to HTML_QuickForm->toHtml()
* line 1048 of /lib/formslib.php: call to HTML_Common->display()
* line 1061 of /lib/formslib.php: call to moodleform->display()
* line 91 of /lib/form/classes/external/dynamic_form.php: call to moodleform->render()
* line ? of unknownfile: call to core_form\external\dynamic_form::execute()
* line 253 of /lib/external/classes/external_api.php: call to call_user_func_array()
* line 88 of /lib/ajax/service.php: call to core_external\external_api::call_external_function()

**Comment by stefanscholz** [comment]
Hi @superfoght ,

Thanks for reporting this issue.

Can you please let us know which MWP version and which version of Video time you use? Is this occurring with MWP theme or with a custom theme?

Best
Stefan

**Comment by superfoght** [comment]
Hey, it is the 1.8.4 package that is installed, provided by our client who has a subscription with you :)

The bug occured in a custom theme we developed based on MWP theme. But I just tested with the default MWP theme and it happens there too.

The MWP version is : Moodle Workplace 4.4.4+ (Build: 20241028)

**Comment by stefanscholz** [comment]
Hi @superfoght ,

we've fixed the issue. Please update the tiny editor plugin (now available on bdecent.de for download, tiny_videotime-1.0-r2) and let me know if you encounter any issues.

Thanks again for reporting the issue!

Best
Stefan

Note: we've also implemented a new capability tiny/videotime:addembed so that administrators can decide who has access to the editor button. We will also make a note in the upcoming Video Time 1.8.5 release notes about this change.

**Comment by Mikkeljeppesen1** [comment]
Hi @stefanscholz,

Im a colleauge to @superfoght and unfortunately, we get the following error if we try to edit a text-block on /my.

Moodleversion: 4.4.6
Pluginversion: tiny_videotime-1.0-r2 (2024051801)

Let me know if you want more explenation :) 

Error code: codingerror
* line 977 of /lib/classes/context.php: coding_exception thrown
* line 152 of /lib/classes/context/block.php: call to core\context->get_course_context()
* line 59 of /lib/editor/tiny/plugins/videotime/classes/plugininfo.php: call to core\context\block->get_course_context()
* line 64 of /lib/editor/tiny/classes/manager.php: call to tiny_videotime\plugininfo::is_enabled()
* line 200 of /lib/editor/tiny/classes/editor.php: call to editor_tiny\manager->get_plugin_configuration()
* line 433 of /lib/form/editor.php: call to editor_tiny\editor->use_editor()
* line 192 of /lib/pear/HTML/QuickForm/Renderer/Tableless.php: call to MoodleQuickForm_editor->toHtml()
* line 3503 of /lib/formslib.php: call to HTML_QuickForm_Renderer_Tableless->renderElement()
* line 432 of /lib/pear/HTML/QuickForm/element.php: call to MoodleQuickForm_Renderer->renderElement()
* line 1644 of /lib/pear/HTML/QuickForm.php: call to HTML_QuickForm_element->accept()
* line 2130 of /lib/formslib.php: call to HTML_QuickForm->accept()
* line 1687 of /lib/pear/HTML/QuickForm.php: call to MoodleQuickForm->accept()
* line 445 of /lib/pear/HTML/Common.php: call to HTML_QuickForm->toHtml()
* line 1048 of /lib/formslib.php: call to HTML_Common->display()
* line 1061 of /lib/formslib.php: call to moodleform->display()
* line 91 of /lib/form/classes/external/dynamic_form.php: call to moodleform->render()
* line ? of unknownfile: call to core_form\external\dynamic_form::execute()
* line 253 of /lib/external/classes/external_api.php: call to call_user_func_array()
* line 88 of /lib/ajax/service.php: call to core_external\external_api::call_external_function()

**Comment by superfoght** [comment]
Yes, it is indeed still an issue also. @stefanscholz can you reopen the issue?
